# Generated by Django 3.0.5 on 2020-05-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200520_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='owner',
        ),
    ]
